name: Build Tauri Application

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Setup Rust (required by Tauri)
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Install Tauri CLI globally
      - name: Install Tauri CLI
        run: cargo install tauri-cli

      # Install dependencies
      - name: Install Node.js dependencies
        run: npm install

      # Build the Tauri application
      - name: Build Tauri application
        run: npm run tauri build

      # Save build artefacts
      - name: Upload Build Artefacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-build-${{ matrix.os }}
          path: src-tauri/target/release/bundle/